/* GENERATED by tools/gen_air_decks.py --anchors. DO NOT EDIT.
 *
 * WHAT THE HARNESS NEEDS TO FLY A ROW, and nothing else: the limiter pair it is told to hold, the mass
 * the envelope figures are quoted at, the wing the stall speeds come off, and the two schedule bounds.
 * The EXPECTATIONS — every published figure, its band, its source and its tier — are declarations in
 * test/modules/air/envelope.json, which this same generator writes from this same table, so the number
 * the harness flies to and the number it is judged against cannot drift apart.
 *
 * A1Mach and the two limiter settings appear in both files by NECESSITY, not by copy: they bound the
 * climb schedule and set the limiter, and they are also what the row is judged on. */
#ifndef FBAIRANCHORS_H
#define FBAIRANCHORS_H

namespace FlightBox::Test {

struct FBAirAnchorRow {
  const char *Key;
  const char *Name;
  double A1Mach, A1AltM;      /* the climb schedule's own cap, and the altitude Vmax is flown at */
  double A5G;                 /* the g LIMITER's setting; 0 = [TODO], the harness then [SET]s 7.0 */
  double AlphaLimitDeg;       /* the alpha LIMITER's setting */
  double EmptyKg, GrossKg, FuelKg;
  double WingAreaM2, ClMax;          /* the wing the 1 g stall speed and the rotation speed come off */
  double ClAtAlphaLimit;             /* the lift the ALPHA LIMITER allows, which is what a pull reaches */
  double PitchStickMax;              /* systems/FBFlightControl's cap [DERIVED], recipe §6.1 */
};

inline constexpr FBAirAnchorRow kAirAnchors[] = {
    {"f15c", "F-15C Eagle", 2.500, 12000.0, 9.0, 22.0, 13154.0, 20185.0, 6103.0, 56.48, 1.249, 1.086, 0.273},
    {"su27", "Su-27S", 2.350, 12000.0, 9.0, 24.0, 16380.0, 23430.0, 9400.0, 62.00, 1.420, 1.235, 0.278},
    {"mig21", "MiG-21bis", 2.050, 13000.0, 8.5, 20.0, 5875.0, 8725.0, 2750.0, 23.00, 0.938, 0.846, 0.203},
    {"mig23", "MiG-23MLD", 2.350, 12000.0, 8.5, 18.0, 11330.0, 14840.0, 3410.0, 37.35, 1.389, 1.208, 0.206},
    {"mig25", "MiG-25PD", 3.100, 13000.0, 4.5, 12.0, 20000.0, 36720.0, 14570.0, 61.40, 0.796, 0.692, 0.127},
    {"mig17", "MiG-17F", 0.930, 3000.0, 8.0, 20.0, 3919.0, 5340.0, 1170.0, 22.60, 1.384, 1.186, 0.271},
    {"su7", "Su-7BKL", 1.740, 11000.0, 0.0, 18.0, 8940.0, 13570.0, 3220.0, 34.00, 0.983, 0.854, 0.198},
    {"su22", "Su-17M4 / Su-22M4", 1.700, 11000.0, 7.0, 18.0, 12160.0, 16400.0, 3770.0, 38.50, 1.353, 1.176, 0.185},
    {"mirf1", "Mirage F1C", 2.200, 11000.0, 0.0, 20.0, 7400.0, 10900.0, 4300.0, 25.00, 1.128, 0.981, 0.209},
    {"f5e", "F-5E Tiger II", 1.630, 11000.0, 0.0, 22.0, 4347.0, 7142.0, 2050.0, 17.28, 1.308, 1.225, 0.200},
};

} // namespace FlightBox::Test
#endif
