# Outshine — the library under src/, its declared data under src/assets/, the tests and the mods they
# run under test/. This Makefile lives beside them and is the whole of the build.
#
# THREE TARGETS AND NO OTHERS (CLAUDE.md): build the engine, run the tests, clean.
#
#   make          compile the library entire -> build/liboutshine.a
#   make test     run the fast gate (the regression net); long suites run when named
#   make clean    remove build artifacts
#
# THE LAYERING IS THE BUILD, AND IT IS DECLARED ONCE. test/run.sh's GroupIncludes is the only
# spelling of which source compiles with which includes; `make` delegates to `run.sh --library`,
# which builds every group from those same declarations and archives them. A second include map
# here went stale, left three layers out of the archive, and broke `make` at HEAD (board:1584).
#
# EVERY BUILD RESTATES WHAT THE LIBRARY IS. STATE.md is generated by `run.sh --state` on every
# `make`: the door's verbs, the tier graph, every claim a case covers, every standing red, every
# open item. It is an artefact and lives with the build, never in the tree, so it cannot go stale
# and cannot be edited into a lie.
SHELL := /bin/bash
.DEFAULT_GOAL := all

SELF_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

.PHONY: all test clean

all:             ## compile the library entire -> build/liboutshine.a, and state it -> STATE.md
	@cd $(SELF_DIR) && sh test/run.sh --library
	@cd $(SELF_DIR) && sh test/run.sh --state > STATE.md

test:            ## run the fast gate; name a suite for the long proofs
	@cd $(SELF_DIR) && sh test/run.sh

clean:           ## remove build artifacts
	cd $(SELF_DIR) && rm -rf build
