#!/usr/bin/env python3
"""FlightBox — the pilot tournament: pit intercept-pilot VARIANTS against each other and read out of
the telemetry WHY one of them won.

A variant is a set of `set pilot_* <value>` lines (systems/FBPilotTuning, doc/mission-format.md), i.e.
mission DATA — so this tool writes .fbm files and runs the existing headless client. Nothing is
compiled between two candidates and there is no tournament code inside the simulator.

    tools/fb_tournament.py --variants tools/variants-bvr.txt --out /tmp/tourney

WHAT IT RUNS. Every unordered pair of variants, in BOTH seat assignments (A west / B east and B west /
A east), on one starting geometry. Flying both seats is what removes a positional advantage from the
result: the two runs of a pair are mirror images of each other, so the SUM over them measures the
variant and not the seat. Runs go through `fb-gym --threads N` — the simulator's own per-unit
parallelism — and are byte-reproducible whatever N is (that is `--check-determinism`).

THE FITNESS is derived and defended in `Score()` below. In one line: the outcome dominates (+1000 for
a kill, -1200 for being killed), never engaging is punished harder than any craft term can repay, and
everything else can only order runs whose outcome was the same.

Stdlib only, no build target, no dependency on anything under sim/build except the fb-gym binary.
"""

import argparse
import concurrent.futures
import csv
import math
import os
import re
import subprocess
import sys

SIM_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------------------------
# The arena. Two intercept pilots, identical in everything a mission file can say except the seat
# they sit in and the `pilot_*` lines of their variant. Head-on, co-altitude, co-speed, both outside
# the APG-68's own search gate at t=0, so both runs start with a real search phase and neither side
# is handed a detection. The ONLY asymmetry left in the file is the order of the two blocks, and the
# seat swap cancels that.
# ---------------------------------------------------------------------------------------------
GEOMETRIES = {
    # name: (west lat, west lon, west alt, west kt, east lat, east lon, east alt, east kt)
    "mirror": (46.90, 6.40, 8000, 420, 46.90, 7.70, 8000, 420),
    # The energy split of missions/bvr-duel-decided.fbm: the seat is worth a great deal here, which is
    # precisely why both seats are flown. It asks a different question than `mirror` — not "who wins an
    # even fight" but "who does better from both ends of an uneven one".
    "split": (46.90, 6.40, 12000, 500, 46.90, 7.55, 6000, 350),
}

UNIT_TPL = """unit {call}
  team {team}
  module f16
  spawn {lat:.5f} {lon:.5f} {alt} {hdg} {kt}
  set gear up
  set fuel_pct 70
  set datalink off
  set fcr_mode crm
  set store 3 aim120
  set store 7 aim120
  set brief_master_arm arm
  set cmds_mode man
  set cmds_program 1
  set cmds_chaff 60
  set cmds_flare 60
  set task intercept
{tuning}  wp {wplat:.5f} {wplon:.5f} {alt} {kt}
  objective kill unit {foe}
  objective survive
"""


def mission_text(name, timeout, geometry, west_var, east_var):
    wlat, wlon, walt, wkt, elat, elon, ealt, ekt = GEOMETRIES[geometry]
    west = UNIT_TPL.format(call="west", team="friendly", lat=wlat, lon=wlon, alt=walt, hdg="90.0",
                           kt=wkt, wplat=wlat, wplon=wlon + 1.95, foe="east",
                           tuning="".join("  set %s %g\n" % kv for kv in sorted(west_var.params.items())))
    east = UNIT_TPL.format(call="east", team="hostile", lat=elat, lon=elon, alt=ealt, hdg="270.0",
                           kt=ekt, wplat=elat, wplon=elon - 1.95, foe="west",
                           tuning="".join("  set %s %g\n" % kv for kv in sorted(east_var.params.items())))
    return ("name %s\ntimeout %d\n\n# generated by tools/fb_tournament.py — do not edit\n"
            "# west = %s   east = %s   geometry = %s\n\n%s\n%s" %
            (name, timeout, west_var.name, east_var.name, geometry, west, east))


class Variant:
    def __init__(self, name, params):
        self.name = name
        self.params = params

    def __repr__(self):
        return "%s(%s)" % (self.name, ", ".join("%s=%g" % kv for kv in sorted(self.params.items())))


def load_variants(path):
    """One variant per line: `<name> key=value key=value ...`; '#' comments, blank lines ignored.
    A bare name is the airframe's own numbers (FBF16Pilot) — the baseline every tournament wants."""
    out = []
    for lineno, raw in enumerate(open(path), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        tok = line.split()
        params = {}
        for t in tok[1:]:
            if "=" not in t:
                sys.exit("%s:%d: '%s' is not key=value" % (path, lineno, t))
            k, v = t.split("=", 1)
            if not k.startswith("pilot_"):
                sys.exit("%s:%d: '%s' is not a pilot parameter (they all start with pilot_)" % (path, lineno, k))
            params[k] = float(v)
        if any(v.name == tok[0] for v in out):
            sys.exit("%s:%d: duplicate variant name '%s'" % (path, lineno, tok[0]))
        out.append(Variant(tok[0], params))
    if len(out) < 2:
        sys.exit("%s: a tournament needs at least two variants" % path)
    return out


# ---------------------------------------------------------------------------------------------
# Reading a run back
# ---------------------------------------------------------------------------------------------
class Side:
    """One unit's debrief, straight out of its own telemetry file plus the runner's verdict lines."""

    def __init__(self, name):
        self.name = name
        self.result = "NONE"
        self.reason = ""
        self.effective = True
        self.hits = 0
        self.eng = {}
        self.es_start = 0.0

    def g(self, key, default=-1.0):
        v = self.eng.get(key, default)
        return default if v is None else v


def read_side(path, name):
    s = Side(name)
    with open(path, newline="") as f:
        rows = list(csv.reader(f))
    head, last = rows[0], rows[-1]
    idx = {h: i for i, h in enumerate(head)}

    def num(row, key):
        try:
            return float(row[idx[key]])
        except (KeyError, ValueError, IndexError):
            return None

    for h in head:
        if h.startswith("eng_") and h != "eng_state":
            s.eng[h] = num(last, h)
    s.eng["eng_state"] = last[idx["eng_state"]] if "eng_state" in idx else "?"
    s.effective = (num(last, "dmg_effective") or 0.0) > 0.5
    s.hits = int(num(last, "dmg_hits") or 0)
    # Energy height at the moment the engagement began, i.e. the first row that is no longer Idle —
    # the reference the energy term is a fraction OF. Falls back to the first row of the run.
    st = idx.get("eng_state")
    es = idx.get("eng_es")
    if st is not None and es is not None:
        s.es_start = float(rows[1][es]) if len(rows) > 1 else 0.0
        for r in rows[1:]:
            if r[st] != "idle":
                s.es_start = float(r[es])
                break
    return s


RESULT_RE = re.compile(r'UNIT_RESULT unit=(\S+) result=(\S+) reason="([^"]*)"')


def read_run(outdir, west_name, east_name):
    west = read_side(os.path.join(outdir, "telemetry.csv"), west_name)
    east = read_side(os.path.join(outdir, "telemetry_east.csv"), east_name)
    by_call = {"west": west, "east": east}
    duration = 0.0
    for line in open(os.path.join(outdir, "events.log")):
        m = RESULT_RE.search(line)
        if m and m.group(1) in by_call:
            by_call[m.group(1)].result = m.group(2)
            by_call[m.group(1)].reason = m.group(3)
        if "mission SUMMARY" in line:
            d = re.search(r"durationS=([0-9.]+)", line)
            if d:
                duration = float(d.group(1))
    return west, east, duration


# ---------------------------------------------------------------------------------------------
# THE FITNESS
# ---------------------------------------------------------------------------------------------
# Every weight below is stated with the reason it has that size, and the SIZES are the design: the
# outcome band (+1000 / -1200) is larger than everything else put together, so no amount of good
# craft can out-score a kill and no amount of bad craft can talk one away. The craft terms exist to
# ORDER runs that ended the same way, which — since most BVR engagements between equals end in a
# draw — is most of them.
W_KILL = 1000.0     # the point of the sortie
W_DIED = 1200.0     # ...and losing the jet is worth slightly more than killing one: without the
                    # asymmetry a mutual kill would score the same as a stalemate, and "trade every
                    # time" is then a stable strategy against anybody who does not.
W_HIT = 150.0       # THE ANTI-TRIGGER-HAPPY TERM, and the one that pays for AIM the way the outcome
                    # terms pay for RESULT: a burst that went off on the other aircraft (its own
                    # health register counted it) is worth something even when the jet flew on with
                    # its avionics wrecked, and it is the only way a shot earns anything at all. It
                    # cannot be faked — landing a burst means guiding a round to inside ten metres —
                    # and it is a sixth of a kill, so it can never stand in for one.
W_NOSHOT = 250.0    # THE ANTI-RUNNING-AWAY TERM. A pilot that never fires cannot be killed either,
                    # so a pure survival score has its optimum in leaving the area. This is bigger
                    # than every craft term added together, so running away is never a way to place.
W_SHOT_COST = 25.0  # per round fired: an AIM-120 is not free, and a trigger-happy variant that gets
                    # the same kill with three rounds ranks below one that got it with one.
W_QUALITY = 100.0   # the launch geometry, see below
W_SUPPORT = 80.0    # the discriminator between a launch and a kill
W_LEAD = 40.0       # who got the first shot away (relative to the opponent in the SAME run)
W_DEFENCE = 40.0    # answering a warning that was actually made, and living through it
W_ENERGY = 40.0     # the state the engagement is left in


def shot_quality(s):
    """0..1 for the OPENING shot: where inside the launch zone it was taken, times how far off the
    nose the target was. 1.0 = at or inside Rtr, dead ahead — a shot the target cannot outrun and a
    round that does not have to spend its motor turning. 0.0 = fired at Raero, the maximum kinematic
    range, which is the shot a target defeats by turning around. Between the two it is linear.
    A shot deeper than Rtr does not score higher (the plateau): the SMS refuses inside Rmin anyway,
    and rewarding "closer is better" without limit would pay for pressing in, which the outcome terms
    already price far more heavily."""
    r, rtr, raero = s.g("eng_shot_nm"), s.g("eng_shot_rtr_nm"), s.g("eng_shot_raero_nm")
    if r < 0 or rtr < 0 or raero <= rtr:
        return 0.0
    zone = (raero - r) / (raero - rtr)
    zone = max(0.0, min(1.0, zone))
    ata = abs(s.g("eng_shot_ata", 0.0))
    return zone * max(0.0, math.cos(math.radians(min(ata, 90.0))))


def score(me, foe, duration):
    """One side's fitness for one run, plus the itemised reasons — the report prints the items, not
    just the total, because the point of the tournament is WHY."""
    it = []
    total = 0.0

    def add(label, value, detail):
        nonlocal total
        if abs(value) < 1e-9:
            return
        total += value
        it.append((label, value, detail))

    killed_him = not foe.effective
    i_died = not me.effective
    add("kill", W_KILL if killed_him else 0.0, "%s combat-ineffective" % foe.name)
    add("lost", -W_DIED if i_died else 0.0, "shot down (%d hit(s))" % me.hits)
    add("hits landed", W_HIT * foe.hits, "%d burst(s) on %s" % (foe.hits, foe.name))

    shots = int(me.g("eng_shots", 0.0))
    add("no shot", -W_NOSHOT if shots == 0 else 0.0, "never fired a round")
    add("rounds", -W_SHOT_COST * shots, "%d round(s) fired" % shots)

    q = shot_quality(me)
    add("shot geometry", W_QUALITY * q,
        "opening shot %.1f nm (Rtr %.1f, Raero %.1f), %.0f deg off the nose -> q=%.2f" %
        (me.g("eng_shot_nm"), me.g("eng_shot_rtr_nm"), me.g("eng_shot_raero_nm"),
         abs(me.g("eng_shot_ata", 0.0)), q) if shots else "no shot")

    sup = max(0.0, min(1.0, me.g("eng_support_f", 0.0)))
    add("support", W_SUPPORT * sup,
        "held the uplink %.0f%% of the way to the seeker (pitbull=%d)" % (100 * sup, int(me.g("eng_pitbull", 0.0))))

    # WHO SHOT FIRST, measured against the opponent in this very run — a relative term, which is what
    # a duel is. A side that shot while the other never did gets the full mark; the tanh keeps a
    # fifteen-second head start from being worth ten times a five-second one.
    mine, theirs = me.g("eng_shot_s"), foe.g("eng_shot_s")
    if mine >= 0 or theirs >= 0:
        a = mine if mine >= 0 else duration
        b = theirs if theirs >= 0 else duration
        lead = math.tanh((b - a) / 15.0)
        add("shot lead", W_LEAD * lead,
            "first shot at t=%.1f vs %.1f" % (a, b) if mine >= 0 and theirs >= 0
            else ("shot while %s never did" % foe.name if mine >= 0 else "never shot, %s did" % foe.name))

    # DEFENCE is only scored where there was something to defend against, and only if it worked. It
    # cannot be farmed: being shot at is the opponent's decision, not this pilot's, and the term is
    # capped well below what one kill is worth.
    react = me.g("eng_react_s")
    if me.g("eng_threat_s") >= 0 and not i_died:
        d = max(0.0, 1.0 - react / 8.0) if react >= 0 else 0.0
        add("defence", W_DEFENCE * d,
            "answered the warning in %.1f s and lived" % react if react >= 0 else "never answered the warning")

    # ENERGY: the low-water mark of energy height as a fraction of what it started the engagement
    # with. Small on purpose — flying straight and level is perfect on this axis and hopeless on
    # every other one.
    if me.es_start > 1.0:
        frac = max(0.0, min(1.0, me.g("eng_es_min", 0.0) / me.es_start))
        add("energy", W_ENERGY * frac, "energy floor %.0f%% of entry (%.0f -> %.0f ft)" %
            (100 * frac, me.es_start, me.g("eng_es_min", 0.0)))
    return total, it


# ---------------------------------------------------------------------------------------------
# Running
# ---------------------------------------------------------------------------------------------
def run_one(job):
    gym, outroot, tag, text, threads = job
    d = os.path.join(outroot, tag)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "duel.fbm")
    with open(path, "w") as f:
        f.write(text)
    r = subprocess.run([gym, "--mission", path, "--out", d, "--threads", str(threads)],
                       cwd=SIM_DIR, capture_output=True, text=True)
    if not os.path.exists(os.path.join(d, "telemetry_east.csv")):
        sys.exit("run %s produced no telemetry:\n%s%s" % (tag, r.stdout[-2000:], r.stderr[-2000:]))
    return tag, r.returncode


def main():
    ap = argparse.ArgumentParser(description="pilot-variant tournament (see the module docstring)")
    ap.add_argument("--variants", required=True, help="variant file: '<name> pilot_key=value ...' per line")
    ap.add_argument("--out", required=True, help="output directory (one sub-directory per run)")
    ap.add_argument("--gym", default=os.path.join(SIM_DIR, "build", "fb-gym"))
    ap.add_argument("--geometry", default="mirror", choices=sorted(GEOMETRIES))
    ap.add_argument("--timeout", type=int, default=260, help="sim-seconds per run")
    ap.add_argument("--threads", type=int, default=2, help="fb-gym --threads (per-unit step parallelism)")
    ap.add_argument("--jobs", type=int, default=4, help="runs in flight at once (separate processes)")
    ap.add_argument("--check-determinism", action="store_true",
                    help="re-fly every pairing at --threads 1 and 2 and compare the telemetry byte for byte")
    args = ap.parse_args()

    variants = load_variants(args.variants)
    os.makedirs(args.out, exist_ok=True)

    jobs, meta = [], []
    for i in range(len(variants)):
        for j in range(i + 1, len(variants)):
            for west, east in ((variants[i], variants[j]), (variants[j], variants[i])):
                tag = "%s_vs_%s" % (west.name, east.name)
                text = mission_text(tag, args.timeout, args.geometry, west, east)
                jobs.append((args.gym, args.out, tag, text, args.threads))
                meta.append((tag, west, east))

    print("tournament: %d variants, %d pairings, %d runs, geometry=%s, timeout=%ds, threads=%d\n"
          % (len(variants), len(jobs) // 2, len(jobs), args.geometry, args.timeout, args.threads))
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        exits = dict(ex.map(run_one, jobs))

    if args.check_determinism:
        alt = [(args.gym, args.out + "-det", t, x, 1) for (_, _, t, x, _) in jobs]
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as ex:
            list(ex.map(run_one, alt))

    totals = {v.name: 0.0 for v in variants}
    outcomes = {v.name: 0.0 for v in variants}       # the kill/lost/hit part of the score, alone
    runs = {v.name: 0 for v in variants}
    record = {v.name: [0, 0, 0] for v in variants}   # kills, losses, draws
    print("=" * 100)
    print("PAIRINGS — every run, both seat assignments, with the itemised reason for each side")
    print("=" * 100)
    for tag, west, east in meta:
        w, e, duration = read_run(os.path.join(args.out, tag), west.name, east.name)
        ws, wi = score(w, e, duration)
        es, ei = score(e, w, duration)
        totals[west.name] += ws
        totals[east.name] += es
        runs[west.name] += 1
        runs[east.name] += 1
        for items, who in ((wi, west.name), (ei, east.name)):
            outcomes[who] += sum(v for l, v, _ in items if l in ("kill", "lost", "hits landed"))
        for me, foe, who in ((w, e, west.name), (e, w, east.name)):
            if not foe.effective and me.effective:
                record[who][0] += 1
            elif not me.effective:
                record[who][1] += 1
            else:
                record[who][2] += 1
        print("\n%-28s exit=%d  %.1f sim-s" % (tag, exits[tag], duration))
        for side, var, sc, items, other in ((w, west, ws, wi, e), (e, east, es, ei, w)):
            print("  %-6s %-14s %-8s %-42s score %+8.1f" %
                  (side.name, var.name, side.result, side.reason[:42], sc))
            print("       detect %5s  lock %5s  shot %5s  supp %4s  threat %5s  react %5s  defend %5s  shots %d  chaff %d"
                  % (fmt(side.g("eng_detect_s")), fmt(side.g("eng_lock_s")), fmt(side.g("eng_shot_s")),
                     ("%.2f" % side.g("eng_support_f", 0.0)), fmt(side.g("eng_threat_s")),
                     fmt(side.g("eng_react_s")), ("%.1f" % side.g("eng_defend_s", 0.0)),
                     int(side.g("eng_shots", 0.0)), int(side.g("eng_chaff", 0.0))))
            for label, value, detail in items:
                print("       %+8.1f  %-14s %s" % (value, label, detail))

    print("\n" + "=" * 100)
    print("RANKING — fitness is the MEAN over that variant's runs, so it does not grow with the field")
    print("size; `outcome` is the kill/loss/hit part of it alone, `craft` the rest (the part that only")
    print("orders runs which ended the same way).")
    print("=" * 100)
    print("%-16s %9s %9s %8s   %4s %4s %4s   %s" %
          ("variant", "fitness", "outcome", "craft", "kill", "lost", "draw", "parameters"))
    for v in sorted(variants, key=lambda x: -totals[x.name] / max(1, runs[x.name])):
        k, l, d = record[v.name]
        n = max(1, runs[v.name])
        print("%-16s %9.1f %9.1f %8.1f   %4d %4d %4d   %s" %
              (v.name, totals[v.name] / n, outcomes[v.name] / n, (totals[v.name] - outcomes[v.name]) / n,
               k, l, d, " ".join("%s=%g" % kv for kv in sorted(v.params.items())) or "(airframe defaults)"))

    if args.check_determinism:
        bad = 0
        for tag, _, _ in meta:
            for f in ("telemetry.csv", "telemetry_east.csv"):
                a = open(os.path.join(args.out, tag, f), "rb").read()
                b = open(os.path.join(args.out + "-det", tag, f), "rb").read()
                if a != b:
                    print("DETERMINISM FAIL: %s/%s differs between --threads %d and 1" % (tag, f, args.threads))
                    bad += 1
        print("\ndeterminism: %d file(s) differ between --threads %d and --threads 1 (%d pairings)"
              % (bad, args.threads, len(meta)))
        if bad:
            return 1
    return 0


def fmt(v):
    return "-" if v is None or v < 0 else "%.1f" % v


if __name__ == "__main__":
    sys.exit(main())
