/* GENERATED by tools/gen_air_decks.py --anchors. DO NOT EDIT.
 *
 * The eight published anchors per deck row, in the ONE place the deck generator already holds them, so
 * the harness that measures a deck and the recipe that wrote it cannot drift apart. Sources and
 * confidence tiers per number: doc/modules/air/catalogue.md. The BANDS are
 * doc/modules/air/flight-model-recipe.md §7.1 and are DERIVED from the one existing generated-from-
 * anchors deck's own measured misses, rounded outward — a band is not a target, and widening one to
 * admit a deck is the falsification that file exists to prevent. */
#ifndef FBAIRANCHORS_H
#define FBAIRANCHORS_H

namespace FlightBox::Clients {

struct FBAirAnchorRow {
  const char *Key;
  const char *Name;
  double A1Mach, A1AltM;      /* Vmax at altitude */
  double A2Mach;              /* Vmax at sea level; 0 = [TODO] in the catalogue */
  double A3CeilingM;
  double A4RocMs;             /* 0 = the row publishes a TIME to height instead, or nothing */
  double A5G;                 /* 0 = [TODO]; the limiter is then [SET] from the measured CLmax */
  double AlphaLimitDeg;
  double EmptyKg, GrossKg, FuelKg;
  double TakeoffRunM;         /* 0 = not published */
  double WingAreaM2, SpanM, ClMax;   /* A8 + the lift curve's own CLmax, for the ground run's Vr */
  int    Engines;
};

/* THE DEVIATION BANDS (recipe §7.1). */
constexpr double kBandVmaxAlt = 0.05;
constexpr double kBandVmaxSl = 0.05;
constexpr double kBandCeiling = 0.10;
constexpr double kBandRoc = 0.25;
constexpr double kBandG = 0.10;
constexpr double kBandAlpha = 0.05;
constexpr double kBandTurnRate = 0.10;
constexpr double kBandTakeoff = 0.30;
constexpr double kBandMass = 0.01;

inline constexpr FBAirAnchorRow kAirAnchors[] = {
    {"f15c", "F-15C Eagle", 2.500, 12000.0, 1.200, 19812.0, 340.6, 9.0, 22.0, 13154.0, 20185.0, 6103.0, 0.0, 56.48, 13.050, 1.249, 2},
    {"su27", "Su-27S", 2.350, 12000.0, 1.130, 18500.0, 300.0, 9.0, 24.0, 16380.0, 23430.0, 9400.0, 0.0, 62.00, 14.700, 1.420, 2},
    {"mig21", "MiG-21bis", 2.050, 13000.0, 1.060, 17500.0, 0.0, 8.5, 20.0, 5875.0, 8725.0, 2750.0, 830.0, 23.00, 7.154, 0.938, 1},
    {"mig23", "MiG-23MLD", 2.350, 12000.0, 1.140, 18500.0, 230.0, 8.5, 18.0, 11330.0, 14840.0, 3410.0, 450.0, 37.35, 13.965, 1.389, 1},
    {"mig25", "MiG-25PD", 3.100, 13000.0, 1.060, 20700.0, 208.0, 4.5, 12.0, 20000.0, 36720.0, 14570.0, 0.0, 61.40, 14.010, 0.796, 2},
    {"mig17", "MiG-17F", 0.930, 3000.0, 0.890, 16600.0, 65.0, 8.0, 20.0, 3919.0, 5340.0, 1170.0, 0.0, 22.60, 9.628, 1.384, 1},
    {"su7", "Su-7BKL", 1.740, 11000.0, 0.940, 17600.0, 160.0, 0.0, 18.0, 8940.0, 13570.0, 3220.0, 0.0, 34.00, 9.310, 0.983, 1},
    {"su22", "Su-17M4 / Su-22M4", 1.700, 11000.0, 1.130, 14200.0, 230.0, 7.0, 18.0, 12160.0, 16400.0, 3770.0, 0.0, 38.50, 13.680, 1.353, 1},
    {"mirf1", "Mirage F1C", 2.200, 11000.0, 0.000, 20000.0, 243.0, 0.0, 20.0, 7400.0, 10900.0, 4300.0, 0.0, 25.00, 8.400, 1.128, 1},
    {"f5e", "F-5E Tiger II", 1.630, 11000.0, 0.000, 15789.0, 175.3, 0.0, 22.0, 4347.0, 7142.0, 2050.0, 610.0, 17.28, 8.130, 1.308, 2},
};

} // namespace FlightBox::Clients
#endif
