// Reproducible iNav-source extraction for the validator. iNav's control code cannot be #included directly
// (it is coupled to the firmware runtime: posControl, navConfig(), the scheduler), so this pulls the
// SELF-CONTAINED numeric core — the PID controller, the pt1 filter, the fixed-point-ish math helpers, the
// scaling constants, and every default gain — VERBATIM from the pinned inav-src submodule into one header,
// validator/generated/inav_core.h. The validator then calls iNav's OWN navPidApply3/navPidInit/pt1FilterApply4
// (not a hand-copy that drifts). Re-run after an iNav submodule bump; the header carries the source hash.
//
//   node validator/extract_inav.mjs        # -> validator/generated/inav_core.h
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SIM = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = `${SIM}/inav-src/src/main`;
const read = (p) => readFileSync(`${SRC}/${p}`, 'utf8');

/** Extract a C function VERBATIM: from the line matching `sig` to its brace-balanced close. */
function fn(file, sig) {
  const text = read(file), lines = text.split('\n');
  const start = lines.findIndex((l) => new RegExp(sig).test(l));
  if (start < 0) throw new Error(`not found in ${file}: ${sig}`);
  let depth = 0, started = false, out = [];
  for (let i = start; i < lines.length; i++) {
    const l = lines[i]; out.push(l);
    for (const ch of l) { if (ch === '{') { depth++; started = true; } else if (ch === '}') depth--; }
    if (started && depth === 0) break;
  }
  return out.join('\n');
}
/** Extract a `#define NAME ...` line verbatim. */
function def(file, name) {
  const l = read(file).split('\n').find((x) => new RegExp(`^#define\\s+${name}\\b`).test(x));
  if (!l) throw new Error(`#define ${name} not in ${file}`);
  return l;
}
/** Extract a typedef struct/enum block by its closing `} NAME;`. */
function typedefBlock(file, name) {
  const text = read(file), lines = text.split('\n');
  const end = lines.findIndex((l) => new RegExp(`}\\s*${name}\\s*;`).test(l));
  if (end < 0) throw new Error(`typedef ${name} not in ${file}`);
  let start = end; while (start > 0 && !/typedef\s+(struct|enum)/.test(lines[start])) start--;
  return lines.slice(start, end + 1).join('\n');
}
/** iNav setting default_value by name (settings.yaml). */
function settingDefault(name) {
  const y = readFileSync(`${SRC}/fc/settings.yaml`, 'utf8');
  const m = y.match(new RegExp(`name: ${name}\\n(?:.*\\n)*?\\s*default_value:\\s*([0-9.]+)`));
  return m ? Number(m[1]) : null;
}

const gains = [
  'nav_fw_pos_z_p', 'nav_fw_pos_z_i', 'nav_fw_pos_z_d', 'nav_fw_pos_z_ff', 'nav_fw_alt_control_response',
  'nav_fw_pos_xy_p', 'nav_fw_pos_xy_i', 'nav_fw_pos_xy_d',
  'fw_p_pitch', 'fw_i_pitch', 'fw_d_pitch', 'fw_ff_pitch', 'fw_p_roll', 'fw_i_roll', 'fw_d_roll', 'fw_ff_roll',
  'fw_p_level', 'fw_i_level',
  'nav_fw_cruise_thr', 'nav_fw_min_thr', 'nav_fw_max_thr', 'nav_fw_pitch2thr', 'nav_fw_control_smoothness',
];
let srcHash = 'unknown';
try { srcHash = execSync('git -C ' + SIM + '/inav-src rev-parse --short HEAD', { encoding: 'utf8' }).trim(); } catch { /* detached/no-git */ }

const parts = [];
parts.push(`/* GENERATED by validator/extract_inav.mjs from inav-src @ ${srcHash} — DO NOT EDIT.
 * iNav's own numeric control core, extracted verbatim (MPL-2.0 / GPL-3.0, INAV Project). Re-run the
 * extractor after an inav-src submodule bump. Coupled firmware runtime is NOT extracted; the validator
 * wires these primitives into iNav's control-law structure. */
#ifndef FB_INAV_CORE_H
#define FB_INAV_CORE_H
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#ifndef M_PIf
#define M_PIf 3.14159265358979323846f
#endif
#define FAST_CODE
#define NOINLINE
#define US2S(us) ((us) * 1e-6f)
#define SIGN(a) ((a >= 0) ? 1 : -1)
`);
parts.push('/* --- common/maths.c --- */');
parts.push(fn('common/maths.c', '^float FAST_CODE constrainf\\(').replace('FAST_CODE ', ''));
parts.push(fn('common/maths.c', '^float FAST_CODE_[A-Z]* ?scaleRangef\\(|^float scaleRangef\\(|scaleRangef\\(float').replace(/FAST_CODE[A-Z_]* /, ''));
parts.push('/* --- common/filter.{h,c} (pt1) --- */');
parts.push(typedefBlock('common/filter.h', 'pt1Filter_t'));
parts.push(fn('common/filter.c', 'static float FAST_CODE pt1ComputeRC\\(').replace('static float FAST_CODE', 'static float'));
parts.push(fn('common/filter.c', '^float FAST_CODE NOINLINE pt1FilterApply4\\(').replace('FAST_CODE NOINLINE ', ''));
parts.push(fn('common/filter.c', '^void pt1FilterReset\\('));
parts.push('/* --- common/fp_pid.{h,c} --- */');
for (const c of ['FP_PID_RATE_P_MULTIPLIER', 'FP_PID_RATE_I_MULTIPLIER', 'FP_PID_RATE_FF_MULTIPLIER', 'FP_PID_LEVEL_P_MULTIPLIER'])
  parts.push(def('flight/pid.h', c));
parts.push(typedefBlock('common/fp_pid.h', 'pidControllerParam_t'));
parts.push(typedefBlock('common/fp_pid.h', 'pidControllerFlags_e'));
parts.push(typedefBlock('common/fp_pid.h', 'pidController_t'));
parts.push(fn('common/fp_pid.c', '^float navPidApply3\\('));
parts.push(fn('common/fp_pid.c', '^float navPidApply2\\('));
parts.push(fn('common/fp_pid.c', '^void navPidReset\\('));
parts.push(fn('common/fp_pid.c', '^void navPidInit\\('));
parts.push('/* --- navigation constants (navigation_private.h / navigation_fixedwing.c) --- */');
parts.push(def('navigation/navigation_private.h', 'NAV_DTERM_CUT_HZ'));
parts.push(def('navigation/navigation_fixedwing.c', 'NAV_FW_BASE_PITCH_CUTOFF_FREQUENCY_HZ'));
parts.push(def('navigation/navigation_fixedwing.c', 'NAV_FW_BASE_ROLL_CUTOFF_FREQUENCY_HZ'));
parts.push(fn('navigation/navigation_fixedwing.c', 'static float getSmoothnessCutoffFreq\\(')
  .replace('navConfig()->fw.control_smoothness', 'control_smoothness')
  .replace('static float getSmoothnessCutoffFreq(float baseFreq)', 'static float getSmoothnessCutoffFreq(float baseFreq, int control_smoothness)'));
parts.push('/* --- iNav default gains (settings.yaml default_value) --- */');
for (const g of gains) { const v = settingDefault(g); if (v == null) throw new Error(`no default for ${g}`); parts.push(`#define INAV_DEFAULT_${g.toUpperCase()} ${v}`); }
parts.push('#endif /* FB_INAV_CORE_H */');

const outDir = `${SIM}/validator/generated`;
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}/inav_core.h`, parts.join('\n\n') + '\n');
process.stderr.write(`inav_core.h generated from inav-src @ ${srcHash} (${gains.length} default gains)\n`);
