struct M {
  float factor;
  float cut;
  float metalness;
  float roughness;
  vec4 base;
  vec3 emissive;
  float normalScale;
  float identity;
  vec3 f0;
  float specularWeight;
  float transmission;
  float thickness;
  float attenuationDistance;
  vec3 attenuationColour;
  vec3 sheenColour;
  float sheenRoughness;
  float clearcoat;
  float clearcoatRoughness;
  float anisotropy;
  float anisotropyRotation;
  float iridescence;
  float iridescenceIor;
  float iridescenceThicknessMin;
  float iridescenceThicknessMax;
  vec3 colourUvU;
  vec3 colourUvV;
  vec3 normalUvU;
  vec3 normalUvV;
  vec3 metalRoughUvU;
  vec3 metalRoughUvV;
  vec3 emissiveUvU;
  vec3 emissiveUvV;
  vec3 specularStrengthUvU;
  vec3 specularStrengthUvV;
  vec3 specularTintUvU;
  vec3 specularTintUvV;
  float colourUvSecond;
  float normalUvSecond;
  float metalRoughUvSecond;
  float emissiveUvSecond;
  float specularStrengthUvSecond;
  float specularTintUvSecond;
};
layout(std140, set = 3, binding = 0) uniform Material {
  float factor;
  float cut;
  float metalness;
  float roughness;
  float basex;
  float basey;
  float basez;
  float basew;
  float emissivex;
  float emissivey;
  float emissivez;
  float normalScale;
  float identity;
  float f0x;
  float f0y;
  float f0z;
  float specularWeight;
  float transmission;
  float thickness;
  float attenuationDistance;
  float attenuationColourx;
  float attenuationColoury;
  float attenuationColourz;
  float sheenColourx;
  float sheenColoury;
  float sheenColourz;
  float sheenRoughness;
  float clearcoat;
  float clearcoatRoughness;
  float anisotropy;
  float anisotropyRotation;
  float iridescence;
  float iridescenceIor;
  float iridescenceThicknessMin;
  float iridescenceThicknessMax;
  float colourUvUx;
  float colourUvUy;
  float colourUvUz;
  float colourUvVx;
  float colourUvVy;
  float colourUvVz;
  float normalUvUx;
  float normalUvUy;
  float normalUvUz;
  float normalUvVx;
  float normalUvVy;
  float normalUvVz;
  float metalRoughUvUx;
  float metalRoughUvUy;
  float metalRoughUvUz;
  float metalRoughUvVx;
  float metalRoughUvVy;
  float metalRoughUvVz;
  float emissiveUvUx;
  float emissiveUvUy;
  float emissiveUvUz;
  float emissiveUvVx;
  float emissiveUvVy;
  float emissiveUvVz;
  float specularStrengthUvUx;
  float specularStrengthUvUy;
  float specularStrengthUvUz;
  float specularStrengthUvVx;
  float specularStrengthUvVy;
  float specularStrengthUvVz;
  float specularTintUvUx;
  float specularTintUvUy;
  float specularTintUvUz;
  float specularTintUvVx;
  float specularTintUvVy;
  float specularTintUvVz;
  float colourUvSecond;
  float normalUvSecond;
  float metalRoughUvSecond;
  float emissiveUvSecond;
  float specularStrengthUvSecond;
  float specularTintUvSecond;
} packedMaterial;
M materialAt() {
  M m;
  m.factor = float(packedMaterial.factor);
  m.cut = float(packedMaterial.cut);
  m.metalness = float(packedMaterial.metalness);
  m.roughness = float(packedMaterial.roughness);
  m.base = vec4(packedMaterial.basex, packedMaterial.basey, packedMaterial.basez, packedMaterial.basew);
  m.emissive = vec3(packedMaterial.emissivex, packedMaterial.emissivey, packedMaterial.emissivez);
  m.normalScale = float(packedMaterial.normalScale);
  m.identity = float(packedMaterial.identity);
  m.f0 = vec3(packedMaterial.f0x, packedMaterial.f0y, packedMaterial.f0z);
  m.specularWeight = float(packedMaterial.specularWeight);
  m.transmission = float(packedMaterial.transmission);
  m.thickness = float(packedMaterial.thickness);
  m.attenuationDistance = float(packedMaterial.attenuationDistance);
  m.attenuationColour = vec3(packedMaterial.attenuationColourx, packedMaterial.attenuationColoury, packedMaterial.attenuationColourz);
  m.sheenColour = vec3(packedMaterial.sheenColourx, packedMaterial.sheenColoury, packedMaterial.sheenColourz);
  m.sheenRoughness = float(packedMaterial.sheenRoughness);
  m.clearcoat = float(packedMaterial.clearcoat);
  m.clearcoatRoughness = float(packedMaterial.clearcoatRoughness);
  m.anisotropy = float(packedMaterial.anisotropy);
  m.anisotropyRotation = float(packedMaterial.anisotropyRotation);
  m.iridescence = float(packedMaterial.iridescence);
  m.iridescenceIor = float(packedMaterial.iridescenceIor);
  m.iridescenceThicknessMin = float(packedMaterial.iridescenceThicknessMin);
  m.iridescenceThicknessMax = float(packedMaterial.iridescenceThicknessMax);
  m.colourUvU = vec3(packedMaterial.colourUvUx, packedMaterial.colourUvUy, packedMaterial.colourUvUz);
  m.colourUvV = vec3(packedMaterial.colourUvVx, packedMaterial.colourUvVy, packedMaterial.colourUvVz);
  m.normalUvU = vec3(packedMaterial.normalUvUx, packedMaterial.normalUvUy, packedMaterial.normalUvUz);
  m.normalUvV = vec3(packedMaterial.normalUvVx, packedMaterial.normalUvVy, packedMaterial.normalUvVz);
  m.metalRoughUvU = vec3(packedMaterial.metalRoughUvUx, packedMaterial.metalRoughUvUy, packedMaterial.metalRoughUvUz);
  m.metalRoughUvV = vec3(packedMaterial.metalRoughUvVx, packedMaterial.metalRoughUvVy, packedMaterial.metalRoughUvVz);
  m.emissiveUvU = vec3(packedMaterial.emissiveUvUx, packedMaterial.emissiveUvUy, packedMaterial.emissiveUvUz);
  m.emissiveUvV = vec3(packedMaterial.emissiveUvVx, packedMaterial.emissiveUvVy, packedMaterial.emissiveUvVz);
  m.specularStrengthUvU = vec3(packedMaterial.specularStrengthUvUx, packedMaterial.specularStrengthUvUy, packedMaterial.specularStrengthUvUz);
  m.specularStrengthUvV = vec3(packedMaterial.specularStrengthUvVx, packedMaterial.specularStrengthUvVy, packedMaterial.specularStrengthUvVz);
  m.specularTintUvU = vec3(packedMaterial.specularTintUvUx, packedMaterial.specularTintUvUy, packedMaterial.specularTintUvUz);
  m.specularTintUvV = vec3(packedMaterial.specularTintUvVx, packedMaterial.specularTintUvVy, packedMaterial.specularTintUvVz);
  m.colourUvSecond = float(packedMaterial.colourUvSecond);
  m.normalUvSecond = float(packedMaterial.normalUvSecond);
  m.metalRoughUvSecond = float(packedMaterial.metalRoughUvSecond);
  m.emissiveUvSecond = float(packedMaterial.emissiveUvSecond);
  m.specularStrengthUvSecond = float(packedMaterial.specularStrengthUvSecond);
  m.specularTintUvSecond = float(packedMaterial.specularTintUvSecond);
  return m;
}
